// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"context"
	"youtubelist/application/usecase/api"
	"youtubelist/application/usecase/util"
	"youtubelist/util/gcpconfig"
)

// Injectors from wire.go:

func InitUsecaseBase(ctx context.Context, cfg *gcpconfig.GcpConfig) *util.UsecaseBase {
	client := provideFireStoreClient(ctx)
	logger := provideLogger()
	redisClient := provideRedisClient(cfg)
	iTwitter := provideTwitter(ctx, cfg)
	iYoutube := provideYoutube(ctx, cfg)
	iNiconico := provideNiconico()
	iSpotify := provideSpotify(cfg, logger)
	usecaseBase := api.NewUsecaseBase(client, logger, redisClient, iTwitter, iYoutube, iNiconico, iSpotify)
	return usecaseBase
}
